# Generated by Django 6.0.2 on 2026-02-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_options_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('daily', 'Daily Work'), ('hobbies', 'Hobbies'), ('reading', 'Reading'), ('writing', 'Writing'), ('other', 'Other')], default='daily', max_length=20),
        ),
    ]
