# Generated by Django 6.0.2 on 2026-02-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', 'deadline', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('daily', 'Daily Work'), ('reading', 'Reading'), ('writing', 'Writing'), ('hobbies', 'Hobbies'), ('other', 'Other')], default='daily', max_length=20),
        ),
    ]
